name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Installs the latest version of our application
      - name: Checkout
        uses: actions/checkout@v3       
      
      # Installs Node.js 16
      - name: Setup Node.js
        uses: action/setup-node@v3
        with:
          node-version: 16
      
      # Installs production environment dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build Storybook
        run: npm run build-storybook
      
      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env: 
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}